version: '3'
services:
  flask-app:
    build: ./backend
    ports:
      - "5000:5000"

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
